# Generated by Django 5.1.4 on 2025-01-08 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=50,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите время выполнения привычки",
                        null=True,
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Укажите необходимое действие привычки",
                        max_length=150,
                        null=True,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "sign_of_a_pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Приятная привычка",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("every minute", "every minute"),
                            ("every hour", "every hour"),
                            ("every day", "every day"),
                            ("every other day", "every other day"),
                            ("once every three days", "once every three days"),
                            ("once every four days", "once every four days"),
                            ("once every five days", "once every five days"),
                            ("once every six days", "once every six days"),
                            ("once a week", "once a week"),
                        ],
                        default="every day",
                        help_text="Укажите периодичность выполнения",
                        max_length=50,
                        verbose_name="Периодичность выполнения привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=150,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите предположительно потраченное время на привычку",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "sign_of_publicity",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать для общего доступа",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите приятную связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
